### PR TITLE
Improve handling of download errors

### PR DESCRIPTION
**Pull request by baztian**

### CODE REVIEW

**Comment by sunng87** [comment]
Thank you, @baztian. BTW, would you like to join the jip team to maintain this library?

**Comment by baztian** [comment]
Thank you @sunng87. It would be a honour. How do you like to collaborate? Would it be ok for you if I merge stuff that I think it just has the right quality? What about stuff I contribute? A pull request so we have a kind of review or do you want me to merge just right away?

**Comment by sunng87** [comment]
Yes, if you like I may hand over full control of this library to you and @wikier  including the release authority on pypi. The sad fact is I don't use jython any more and had little time/willingness to maintain this tool. I found this tool can still help people and I wish it cound be maintained as long as jython lives.

**Comment by baztian** [comment]
Ok. Thank you. That would be nice. jip is definitly a nice tool and should stay active. I don't have that much motivation to implement tons of new features. But I'm willing to fix it or review PRs, issues and the like.

**Comment by sunng87** [comment]
Thank you, @baztian !

**Pull request merged**
