### PR TITLE
jython-installer 2.7.2 on virtualenv 16.5.0 on Ubuntu Trusty

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by baztian** [comment]
There is now Jython 2.7.2 availabile. But I think [the issue](https://github.com/jythontools/jython/issues/160) is still not resolved

**Comment by baztian** [comment]
Maybe you can give 2.7.2 a try?

**Comment by cclauss** [comment]
https://github.com/pypa/virtualenv/pull/1357
vitrualenv release 16.6.0 drop all references to Jython

virtualenv release 20.0.11 make that explicit
https://virtualenv.pypa.io/en/latest/changelog.html?highlight=jython#v20-0-11-2020-03-18

**Comment by baztian** [comment]
@cclauss work on this one is now finished, right? Shall I merge?

**Comment by cclauss** [comment]
If tests pass then please merge.

**Pull request merged**
